import { motion, AnimatePresence } from 'framer-motion';
import Navbar from './components/Navbar';
import HeroInput from './components/HeroInput';
import TaskCard from './components/TaskCard';
import { useAgentStore } from './store/useAgentStore';

export default function App() {
  const { status, thinkingPhase, result, errorMessage, reset } = useAgentStore();

  return (
    <div className="min-h-screen bg-mesh font-sans flex flex-col overflow-x-hidden">
      <Navbar />
      
      <main className="flex-1 max-w-5xl w-full mx-auto px-6 pb-20">
        
        {/* We use AnimatePresence so components fade out smoothly when removed */}
        <AnimatePresence mode="wait">
          
          {/* STATE 1: IDLE (Show the Input) */}
          {status === 'idle' && (
            <motion.div key="input" exit={{ opacity: 0, y: -20 }}>
              <HeroInput />
            </motion.div>
          )}

          {/* STATE 2: ACTIVE OR COMPLETE (Show the Execution Panel) */}
          {status !== 'idle' && (
            <motion.div 
              key="execution"
              initial={{ opacity: 0, y: 20 }} 
              animate={{ opacity: 1, y: 0 }}
              className="mt-12 w-full max-w-3xl mx-auto"
            >
              {/* Header section with Reset Button */}
              <div className="flex justify-between items-end mb-8">
                <div>
                  <h2 className="text-2xl font-bold flex items-center gap-3 text-slate-800 dark:text-white">
                    {status === 'thinking' && '🧠 ' + thinkingPhase}
                    {status === 'complete' && '🎉 Mission Complete'}
                    {status === 'error' && '🚨 Execution Failed'}
                  </h2>
                </div>
                <button onClick={reset} className="text-sm font-medium text-slate-500 hover:text-brand-500 transition-colors">
                  Start Over
                </button>
              </div>

              {/* Error Message Display */}
              {errorMessage && (
                <div className="p-4 bg-red-100 dark:bg-red-900/20 text-red-600 dark:text-red-400 border border-red-200 dark:border-red-800 rounded-xl mb-6">
                  {errorMessage}
                </div>
              )}

              {/* The Fake Visualized Graph Pipeline */}
              {/* In a real app, this array would be dynamically generated by the backend! */}
              <div className="space-y-3 mb-8">
                <TaskCard 
                  title="Fetch match data (MatchAPI)" 
                  status={status === 'complete' ? 'done' : 'running'} 
                  index={0} 
                />
                <TaskCard 
                  title="Fetch player performance (PlayerStatsAPI)" 
                  status={status === 'complete' ? 'done' : status === 'thinking' && thinkingPhase === 'Executing tools...' ? 'running' : 'pending'} 
                  index={1} 
                />
                <TaskCard 
                  title="Generate summary report" 
                  status={status === 'complete' ? 'done' : 'pending'} 
                  index={2} 
                />
              </div>

              {/* Final JSON Result Section */}
              {result && (
                <motion.div 
                  initial={{ opacity: 0, scale: 0.95 }} 
                  animate={{ opacity: 1, scale: 1 }}
                  className="rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800 shadow-xl"
                >
                  {/* Fake MacOS style window header */}
                  <div className="bg-slate-100 dark:bg-slate-800 px-4 py-3 border-b border-slate-200 dark:border-slate-700 flex gap-2">
                    <span className="w-3 h-3 rounded-full bg-red-500"></span>
                    <span className="w-3 h-3 rounded-full bg-yellow-500"></span>
                    <span className="w-3 h-3 rounded-full bg-green-500"></span>
                  </div>
                  {/* The Code Viewer */}
                  <div className="p-6 bg-slate-950 text-emerald-400 font-mono text-sm overflow-x-auto">
                    <pre>{JSON.stringify(result, null, 2)}</pre>
                  </div>
                </motion.div>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </div>
  );
}